version: "3.8"

services:
  postgresdb:
    env_file:
      - ./.env
    image: postgres:latest
    volumes:
      - db-data:/home/codytech/postgresdb/data
    networks:
      - codytech-network
    container_name: "codytechDB"
    restart: "always"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
  # codytech-server:
  #   build: .
  #   env_file:
  #     - ./.env
  #   image: codytech-server
  #   volumes:
  #     - server-data:/home/codytech/server
  #     - node_modules:/home/codytech/server/node_modules
  #   environment:
  #     - POSTGRES_URL=postgresdb
  #   networks:
  #     - codytech-network
  #   depends_on:
  #     - postgresdb
  #   container_name: "codytech-server"
  #   command: 
  #     - yarn migration:up
  #     - yarn prod
  #   ports:
  #     - ${HTTP_PORT}:${HTTP_PORT}
  #   deploy:
  #     update_config:
  #       parallelism: 2
  #     restart_policy:
  #       condition: on-failure

networks:
  codytech-network:
volumes: 
  node_modules:
  server-data:
  db-data: